// formationTemplates.js
const formationTemplates = {
    // 3 Defenders
    '4-4-2': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '4-5-1 (DM, wide players)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '4-3-3 (DM, 3 strikers)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Left Winger (LW)': { role: '', focus: '' },
        'Right Winger (RW)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '4-2-3-1 (AM, wide players)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Left Winger (LW)': { role: '', focus: '' },
        'Right Winger (RW)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '4-2-1-3 (AM, 3 strikers)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '4-3-1-2 (diamond)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '3-4-3 (wide players, 3 strikers)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Left Winger (LW)': { role: '', focus: '' },
        'Right Winger (RW)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '3-5-2 (DM, wide players)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '3-4-1-2 (AM, wide players)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '3-5-1-1 (diamond, wide players)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '3-3-1-3 (diamond, 3 strikers)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Central Midfielder (CM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '5-4-1 (wide players)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '5-2-3 (3 strikers)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '5-3-2 (DM)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Left Midfielder (LM)': { role: '', focus: '' },
        'Central Midfielder (CM)': { role: '', focus: '' },
        'Right Midfielder (RM)': { role: '', focus: '' },
        'Striker (ST)': { role: '', focus: '' }
      },
      '5-2-1-2 (AM)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Left Central Midfielder (LCM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Right Central Midfielder (RCM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      },
      '5-3-1-1 (diamond)': {
        'Goalkeeper (GK)': { role: '', focus: '' },
        'Left Back (LB)': { role: '', focus: '' },
        'Left Center Back (LCB)': { role: '', focus: '' },
        'Center Back (CB)': { role: '', focus: '' },
        'Right Center Back (RCB)': { role: '', focus: '' },
        'Right Back (RB)': { role: '', focus: '' },
        'Defensive Midfielder (CDM)': { role: '', focus: '' },
        'Central Midfielder (CM)': { role: '', focus: '' },
        'Attacking Midfielder (CAM)': { role: '', focus: '' },
        'Left Striker (LST)': { role: '', focus: '' },
        'Right Striker (RST)': { role: '', focus: '' }
      }
      
};
  
  export default formationTemplates;
  